#!/bin/bash

SCRIPTFOLDER=$(pwd)

VERSION=$(./get-version)

cd ../dist

find . -type d | grep $VERSION | xargs -l rm -rf

rm *.bat

cat $SCRIPTFOLDER/win-installer/installer.nsi | sed "s/__VERSION__/$VERSION/" | sed "s/__APPFILE__/qwatch/" | sed "s/__APPNAME__/QWatch/" > qwatch.nsi
cat $SCRIPTFOLDER/win-installer/installer.nsi | sed "s/__VERSION__/$VERSION/" | sed "s/__APPFILE__/iswatch/" | sed "s/__APPNAME__/ISWatch/" > iswatch.nsi

cp $SCRIPTFOLDER/win-installer/res/* .

makensis qwatch.nsi
makensis iswatch.nsi

rm *.nsi *.TXT *.bmp *.ico

mv iswatch.exe iswatch-$VERSION.exe
mv qwatch.exe qwatch-$VERSION.exe

upx -9 iswatch-$VERSION.exe
upx -9 qwatch-$VERSION.exe
