#!/bin/bash

SCRIPTFOLDER=$(pwd)

TMPFILE=/tmp/qwatch-$RANDOM-$RANDOM

svn export http://qwatch.googlecode.com/svn/trunk/ $TMPFILE

cd $TMPFILE

find . | grep Makefile | xargs -l rm		
find . | grep \\.user | xargs -l rm


cd scripts

VERSION=$(./get-version)

cd ..

mkdir qwatch-$VERSION

mv * qwatch-$VERSION/

tar czf qwatch-$VERSION.tar.gz qwatch-$VERSION

cd $SCRIPTFOLDER

cd ..

rm -rf dist

mkdir dist
cd dist

cp $TMPFILE/qwatch-$VERSION.tar.gz .

rm -rf $TMPFILE