#!/bin/bash

cd ..

rm build/*
rm build/app/*
rm build/tests/*
#rm -rf dist

status="$(svn status)"

if [ "$status" != "" ]
then
    revision=$(svn info src-app/src/version.h | grep Revision | awk '{print $2}')
    echo "// Rev $revision, " $(date) >> src-app/src/version.h
    for file in $(svn status | grep -v ! | awk '{print $2}')
    do
	svn add $file
	sourcefile=$(echo $file | egrep "\\.(h|cpp|pro|txt)$")
	if [ "$sourcefile" != "" ]
	then
	    svn propset svn:keywords "Id Rev Date" $file
	fi
    done
    for file in $(svn status | grep ! | awk '{print $2}')
    do
	svn delete $file
    done
    svn commit
fi